apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: goledge-api
  namespace: goledge
  labels:
    app.kubernetes.io/name: goledge
    app.kubernetes.io/component: api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goledge
      app.kubernetes.io/component: api
