apiVersion: v1
kind: Secret
metadata:
  name: goledge-secret
  namespace: goledge
  labels:
    app.kubernetes.io/name: goledge
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  DATABASE_URL: "postgres://ledger:ledger@postgres.goledge.svc.cluster.local:5432/ledger?sslmode=disable"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
