apiVersion: v1
kind: Service
metadata:
  name: goledge-api
  namespace: goledge
  labels:
    app.kubernetes.io/name: goledge
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: goledge
    app.kubernetes.io/component: api
