apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goledge.fullname" . }}-config
  labels:
    {{- include "goledge.labels" . | nindent 4 }}
data:
  API_ADDR: {{ .Values.config.apiAddress | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  MIGRATIONS_PATH: {{ .Values.config.migrationsPath | quote }}
  DYNAMODB_TABLE: {{ .Values.config.dynamoDBTable | quote }}
  DYNAMODB_ENDPOINT: {{ .Values.config.dynamoDBEndpoint | quote }}
  DYNAMODB_REGION: {{ .Values.config.dynamoDBRegion | quote }}
  AWS_ENDPOINT: {{ .Values.config.awsEndpoint | quote }}
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  SNS_TOPIC_ARN: {{ .Values.config.snsTopicArn | quote }}
  SQS_WALLET_BALANCE_QUEUE_URL: {{ .Values.config.sqsWalletBalanceQueueUrl | quote }}
  SSM_PARAMETER_PATH: {{ .Values.config.ssmParameterPath | quote }}
  AWS_SSM_ENABLED: {{ .Values.config.awsSSMEnabled | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.config.otelEndpoint | quote }}
  OTEL_DISABLED: {{ .Values.config.otelDisabled | quote }}
  PROMETHEUS_METRICS_ENABLED: {{ .Values.config.metricsEnabled | quote }}
